-- AlterTable
ALTER TABLE `Goal` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'L1_APPROVED', 'REVISION_REQUESTED', 'APPROVED_LOCKED', 'IN_PROGRESS', 'COMPLETED', 'CLOSED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `GoalSheet` ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `managerFeedback` VARCHAR(191) NULL,
    ADD COLUMN `reviewedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'REVISION_REQUESTED', 'APPROVED_LOCKED') NOT NULL DEFAULT 'DRAFT';
